"""Add tenant-user link

Revision ID: 0e914e712c11
Revises: 48ca82ac12a2
Create Date: 2026-07-13 00:52:51.606145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0e914e712c11"
down_revision: Union[str, None] = "48ca82ac12a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenants", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_tenants_user_id"), "tenants", ["user_id"], unique=True)
    op.create_foreign_key(None, "tenants", "users", ["user_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tenants", type_="foreignkey")
    op.drop_index(op.f("ix_tenants_user_id"), table_name="tenants")
    op.drop_column("tenants", "user_id")
    # ### end Alembic commands ###
