"""Add email uniqueness constraint for Tenant model.

Revision ID: 20dc3a8be02c
Revises: 399e380aa827
Create Date: 2026-08-10 09:51:39.156708

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20dc3a8be02c'
down_revision: Union[str, None] = '399e380aa827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_email', table_name='tenants')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_index('ix_tenants_email', 'tenants', ['email'], unique=False)
    # ### end Alembic commands ###
