"""Add password_changed_at in User model.

Revision ID: 399e380aa827
Revises: 0e914e712c11
Create Date: 2026-08-06 08:47:14.912034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "399e380aa827"
down_revision: Union[str, None] = "0e914e712c11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.alter_column("users", "password_changed_at", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_changed_at")
    # ### end Alembic commands ###
