"""Add property name and address constraint

Revision ID: 48ca82ac12a2
Revises: 1dce13f082b1
Create Date: 2026-07-09 09:14:54.141106

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48ca82ac12a2"
down_revision: Union[str, None] = "1dce13f082b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_property_name_address",
        "properties",
        ["name", "address"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_property_name_address", "properties", type_="unique")
    # ### end Alembic commands ###
