"""Create Properties Table

Revision ID: 532a26d66e4e
Revises: 
Create Date: 2026-05-13 02:14:33.305753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '532a26d66e4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rental_type', sa.Enum('long_term', 'short_term', name='rentaltype'), nullable=False),
    sa.Column('listing_platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('vacant', 'occupied', name='propertystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("listing_platform IN ('direct', 'airbnb', 'booking', 'agoda')", name='ck_property_listing_platform'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
